'use client';
import {useEffect,useState} from 'react'; import AppSidebar from '../AppSidebar'; import '../calibragem/calibragem.css'; import './configuracoes.css';
const SKILLS=['Comunicação','Vendas','Liderança','Negociação','Raciocínio','Apresentação','Tomada de Decisão','Influência'],KEY='noza-user-personalization-v1';
const initial:any={name:'Sandro Bello',role:'',area:'',goal:'',skills:['Comunicação'],style:'Direto',demand:'Exigente',meta:'',notifications:true,calibration:true,patterns:true};
export default function Configuracoes(){const[p,setP]=useState(initial),[saved,setSaved]=useState(false);useEffect(()=>{try{const v=localStorage.getItem(KEY);if(v)setP({...initial,...JSON.parse(v)})}catch{}},[]);const set=(k:string,v:any)=>{setP((x:any)=>({...x,[k]:v}));setSaved(false)},toggle=(v:string)=>set('skills',p.skills.includes(v)?p.skills.filter((x:string)=>x!==v):p.skills.length<3?[...p.skills,v]:p.skills),save=()=>{localStorage.setItem(KEY,JSON.stringify(p));setSaved(true)};
return <main className="cal-shell"><AppSidebar name={p.name}/><section className="cal-main settings-main"><div className="cal-top"><span>NOZA / PERSONALIZAÇÃO</span><span>CONFIGURAÇÕES</span></div><section className="settings-head"><div className="cal-kicker"><i/> SUA NOZA</div><h1>Configure como a NOZA<br/><em>acompanha sua evolução.</em></h1><p>Suas prioridades ajudam a NOZA a observar os padrões mais relevantes e entregar orientações mais alinhadas ao que você quer desenvolver.</p></section><div className="settings-grid">
<section className="settings-card"><span>01 · MEU PERFIL</span><h2>Contexto profissional</h2><div className="field-grid">{[['name','Nome'],['role','Profissão ou cargo'],['area','Área de atuação'],['goal','Objetivo profissional']].map(([k,l])=><label key={k}>{l}<input value={p[k]} onChange={e=>set(k,e.target.value)}/></label>)}</div></section>
<section className="settings-card settings-wide"><span>02 · PERSONALIZAR MINHA NOZA</span><h2>O que você quer desenvolver agora?</h2><p>Escolha até 3 prioridades. A NOZA usará essas áreas para direcionar a atenção sobre seus padrões.</p><div className="skill-picks">{SKILLS.map(x=><button className={p.skills.includes(x)?'on':''} onClick={()=>toggle(x)} key={x}>{x}<b>{p.skills.includes(x)?'✓':'+'}</b></button>)}</div></section>
{[['03 · ESTILO DA NOZA','Como quer receber feedback?','style',['Direto','Analítico','Didático']],['04 · NÍVEL DE EXIGÊNCIA','Profundidade do feedback','demand',['Equilibrado','Exigente','Muito exigente']]].map((a:any)=><section className="settings-card" key={a[0]}><span>{a[0]}</span><h2>{a[1]}</h2><div className="choice-row">{a[3].map((x:string)=><button className={p[a[2]]===x?'on':''} onClick={()=>set(a[2],x)} key={x}>{x}</button>)}</div><small>{a[2]==='style'?'Isso muda a forma de comunicação, não a avaliação da sua performance.':'A exigência altera profundidade e rigor do feedback, nunca artificialmente seu score.'}</small></section>)}
<section className="settings-card"><span>05 · META ATUAL</span><h2>Defina seu próximo desenvolvimento</h2><textarea value={p.meta} onChange={e=>set('meta',e.target.value)} placeholder="Ex.: Quero melhorar minha argumentação em conversas comerciais."/></section>
<section className="settings-card"><span>06 · NOTIFICAÇÕES</span><h2>O que merece sua atenção</h2>{[['notifications','Evolução detectada'],['calibration','Lembrete de calibragem'],['patterns','Novo padrão identificado']].map(([k,l])=><label className="switch-line" key={k}><span>{l}</span><input type="checkbox" checked={p[k]} onChange={e=>set(k,e.target.checked)}/><i/></label>)}</section>
<section className="settings-card"><span>07 · PRIVACIDADE E DADOS</span><h2>Seus dados na NOZA</h2>{['Dados usados pela IA','Exportar meus dados','Gerenciar histórico'].map(x=><button className="settings-link" key={x}>{x}<b>→</b></button>)}</section>
<section className="settings-card"><span>08 · CONTA E PLANO</span><h2>NOZA Pro</h2>{['Gerenciar assinatura','E-mail e segurança'].map(x=><button className="settings-link" key={x}>{x}<b>→</b></button>)}</section></div><div className="settings-save"><span>{saved?'PREFERÊNCIAS SALVAS':'Personalize a experiência da sua NOZA.'}</span><button onClick={save}>{saved?'SALVO ✓':'SALVAR CONFIGURAÇÕES →'}</button></div></section></main>}