'use client';
import {useEffect,useState} from 'react'; import AppSidebar from '../AppSidebar'; import '../calibragem/calibragem.css'; import './configuracoes.css';
const SKILLS=['Comunicação','Vendas','Liderança','Negociação','Raciocínio','Apresentação','Tomada de Decisão','Influência'],KEY='noza-user-personalization-v1';
const initial:any={name:'Sandro Bello',role:'',area:'',goal:'',skills:['Comunicação'],style:'Direto',demand:'Exigente',meta:'',notifications:true,calibration:true,patterns:true};
function cropPhoto(file:File,ratio:'profile'|'space'){return new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onerror=()=>reject(new Error('Não foi possível ler a imagem.'));reader.onload=()=>{const image=new Image();image.onerror=()=>reject(new Error('Escolha uma imagem válida.'));image.onload=()=>{const targetRatio=ratio==='profile'?1:9/16;let sw=image.naturalWidth,sh=image.naturalHeight;if(sw/sh>targetRatio)sw=sh*targetRatio;else sh=sw/targetRatio;const canvas=document.createElement('canvas');canvas.width=ratio==='profile'?320:225;canvas.height=ratio==='profile'?320:400;const ctx=canvas.getContext('2d');if(!ctx)return reject(new Error('Não foi possível preparar a imagem.'));ctx.drawImage(image,(image.naturalWidth-sw)/2,(image.naturalHeight-sh)/2,sw,sh,0,0,canvas.width,canvas.height);resolve(canvas.toDataURL('image/jpeg',.74))};image.src=String(reader.result||'')};reader.readAsDataURL(file)})}

export default function Configuracoes(){const[p,setP]=useState(initial),[saved,setSaved]=useState(false),[profilePhoto,setProfilePhoto]=useState(''),[spacePhoto,setSpacePhoto]=useState(''),[photoError,setPhotoError]=useState('');useEffect(()=>{try{const v=localStorage.getItem(KEY);if(v)setP({...initial,...JSON.parse(v)});setProfilePhoto(localStorage.getItem('zyvo-profile-avatar')||'');setSpacePhoto(localStorage.getItem('zyvo-space-avatar')||'')}catch{}},[]);const set=(k:string,v:any)=>{setP((x:any)=>({...x,[k]:v}));setSaved(false)},toggle=(v:string)=>set('skills',p.skills.includes(v)?p.skills.filter((x:string)=>x!==v):p.skills.length<3?[...p.skills,v]:p.skills),uploadPhoto=async(file:File|null,kind:'profile'|'space')=>{if(!file)return;try{setPhotoError('');const data=await cropPhoto(file,kind);if(kind==='profile'){localStorage.setItem('zyvo-profile-avatar',data);setProfilePhoto(data)}else{localStorage.setItem('zyvo-space-avatar',data);setSpacePhoto(data)}setSaved(false)}catch(e){setPhotoError(e instanceof Error?e.message:'Não foi possível salvar a foto.')}},removePhoto=(kind:'profile'|'space')=>{if(kind==='profile'){localStorage.removeItem('zyvo-profile-avatar');setProfilePhoto('')}else{localStorage.removeItem('zyvo-space-avatar');setSpacePhoto('')}setSaved(false)},save=()=>{localStorage.setItem(KEY,JSON.stringify(p));localStorage.setItem('noza-profile-name',p.name||'Participante');setSaved(true)};
return <main className="cal-shell"><AppSidebar name={p.name}/><section className="cal-main settings-main"><div className="cal-top"><span>NOZA / PERSONALIZAÇÃO</span><span>CONFIGURAÇÕES</span></div><section className="settings-head"><div className="cal-kicker"><i/> SUA NOZA</div><h1>Configure como a NOZA<br/><em>acompanha sua evolução.</em></h1><p>Suas prioridades ajudam a NOZA a observar os padrões mais relevantes e entregar orientações mais alinhadas ao que você quer desenvolver.</p></section><div className="settings-grid">
<section className="settings-card"><span>01 · MEU PERFIL</span><h2>Contexto profissional</h2><div className="field-grid">{[['name','Nome'],['role','Profissão ou cargo'],['area','Área de atuação'],['goal','Objetivo profissional']].map(([k,l])=><label key={k}>{l}<input value={p[k]} onChange={e=>set(k,e.target.value)}/></label>)}</div></section>
<section className="settings-card settings-wide"><span>02 · PERSONALIZAR MINHA NOZA</span><h2>O que você quer desenvolver agora?</h2><p>Escolha até 3 prioridades. A NOZA usará essas áreas para direcionar a atenção sobre seus padrões.</p><div className="skill-picks">{SKILLS.map(x=><button className={p.skills.includes(x)?'on':''} onClick={()=>toggle(x)} key={x}>{x}<b>{p.skills.includes(x)?'✓':'+'}</b></button>)}</div></section>
{[['03 · ESTILO DA NOZA','Como quer receber feedback?','style',['Direto','Analítico','Didático']],['04 · NÍVEL DE EXIGÊNCIA','Profundidade do feedback','demand',['Equilibrado','Exigente','Muito exigente']]].map((a:any)=><section className="settings-card" key={a[0]}><span>{a[0]}</span><h2>{a[1]}</h2><div className="choice-row">{a[3].map((x:string)=><button className={p[a[2]]===x?'on':''} onClick={()=>set(a[2],x)} key={x}>{x}</button>)}</div><small>{a[2]==='style'?'Isso muda a forma de comunicação, não a avaliação da sua performance.':'A exigência altera profundidade e rigor do feedback, nunca artificialmente seu score.'}</small></section>)}
<section className="settings-card"><span>05 · META ATUAL</span><h2>Defina seu próximo desenvolvimento</h2><textarea value={p.meta} onChange={e=>set('meta',e.target.value)} placeholder="Ex.: Quero melhorar minha argumentação em conversas comerciais."/></section>
<section className="settings-card"><span>06 · NOTIFICAÇÕES</span><h2>O que merece sua atenção</h2>{[['notifications','Evolução detectada'],['calibration','Lembrete de calibragem'],['patterns','Novo padrão identificado']].map(([k,l])=><label className="switch-line" key={k}><span>{l}</span><input type="checkbox" checked={p[k]} onChange={e=>set(k,e.target.checked)}/><i/></label>)}</section>
<section className="settings-card"><span>07 · PRIVACIDADE E DADOS</span><h2>Seus dados na NOZA</h2>{['Dados usados pela IA','Exportar meus dados','Gerenciar histórico'].map(x=><button className="settings-link" key={x}>{x}<b>→</b></button>)}</section>
<section className="settings-card"><span>08 · CONTA E PLANO</span><h2>NOZA Pro</h2>{['Gerenciar assinatura','E-mail e segurança'].map(x=><button className="settings-link" key={x}>{x}<b>→</b></button>)}</section>
<section className="settings-card"><span>09 · FOTO DE PERFIL</span><h2>Imagem quadrada · 1:1</h2><p>Use uma foto para identificar seu perfil na NOZA. A imagem será ajustada para o formato quadrado.</p><div className="settings-photo-row"><div className="settings-photo-preview profile">{profilePhoto?<img src={profilePhoto} alt="Prévia da foto de perfil"/>:<span>1:1</span>}</div><div className="settings-photo-actions"><label className="settings-photo-button">Escolher foto<input type="file" accept="image/*" onChange={e=>void uploadPhoto(e.currentTarget.files?.[0]||null,'profile')}/></label>{profilePhoto&&<button type="button" className="settings-photo-remove" onClick={()=>removePhoto('profile')}>Remover</button>}<small>JPG, PNG ou WebP</small></div></div></section>
<section className="settings-card"><span>10 · FOTO DO SPACE</span><h2>Imagem vertical · 9:16</h2><p>Esta foto aparece na tela da chamada quando sua câmera estiver desligada. É independente da foto do perfil.</p><div className="settings-photo-row"><div className="settings-photo-preview space">{spacePhoto?<img src={spacePhoto} alt="Prévia da foto do Space"/>:<span>9:16</span>}</div><div className="settings-photo-actions"><label className="settings-photo-button">Escolher foto<input type="file" accept="image/*" onChange={e=>void uploadPhoto(e.currentTarget.files?.[0]||null,'space')}/></label>{spacePhoto&&<button type="button" className="settings-photo-remove" onClick={()=>removePhoto('space')}>Remover</button>}<small>JPG, PNG ou WebP</small></div></div>{photoError&&<p className="settings-photo-error" role="alert">{photoError}</p>}</section>
</section></div><div className="settings-save"><span>{saved?'PREFERÊNCIAS SALVAS':'Personalize a experiência da sua NOZA.'}</span><button onClick={save}>{saved?'SALVO ✓':'SALVAR CONFIGURAÇÕES →'}</button></div></section></main>}