'use client';
import AppTopbar from '../AppTopbar';

import { Check, Crown, Gem, Sparkles, Building2 } from 'lucide-react';
import { useState } from 'react';
import AppSidebar from '../AppSidebar';
import '../app-topbar.css';
import '../app-sidebar.css';
import '../home-overrides.css';
import './pricing.css';

type Plan = { key:string; name:string; eyebrow:string; monthly:number|null; description:string; aiLabel:string; aiLimit:string; features:string[]; cta:string; note:string; Icon:typeof Sparkles; featured?:boolean };

const plans:Plan[]=[
{key:'pro',name:'Pro',eyebrow:'TRANSFORME SUA PERFORMANCE EM EVOLUÇÃO CONTÍNUA.',monthly:79.9,description:'Para quem quer desenvolver sua performance continuamente com inteligência aplicada às situações reais.',aiLabel:'NOZA IA',aiLimit:'10 horas de análise inteligente por mês',features:['Reuniões NOZA ilimitadas','10h de análise inteligente de reuniões','Human Pro com inteligência avançada','Calibragem Cognitiva','Skills + evolução contínua','Memória longitudinal de performance','Comparação entre reuniões','Insights e evidências pós-reunião','Gravações e histórico','Plano de desenvolvimento personalizado','Reuniões em Full HD','Suporte 24h'],cta:'TESTAR PRO POR 7 DIAS',note:'R$ 0 hoje. Após 7 dias, R$ 79,90/mês. Cancele durante o período de experiência e não será cobrado.',Icon:Crown,featured:true},
{key:'performance',name:'Performance',eyebrow:'MAIS CAPACIDADE PARA QUEM USA A NOZA INTENSIVAMENTE.',monthly:129.9,description:'Mais capacidade de análise e memória para transformar um volume maior de reuniões em evolução mensurável.',aiLabel:'TUDO DO PRO, MAIS:',aiLimit:'30 horas de análise inteligente por mês',features:['Reuniões NOZA ilimitadas','30h de análise inteligente de reuniões','Human Pro com uso ampliado','Memória longitudinal avançada','Comparação profunda entre reuniões','Diagnósticos de performance','Identificação de padrões e lacunas','Recomendações estratégicas da IA','Histórico completo de desenvolvimento','Gravações e histórico ampliados','Prioridade no processamento de análises','Suporte prioritário 24h'],cta:'TESTAR PERFORMANCE POR 7 DIAS',note:'R$ 0 hoje. Após 7 dias, R$ 129,90/mês. Cancele durante o período de experiência e não será cobrado.',Icon:Gem},
{key:'business',name:'Business',eyebrow:'PERFORMANCE INTELLIGENCE PARA EQUIPES.',monthly:null,description:'Para empresas que querem desenvolver pessoas e acompanhar a evolução da performance em escala.',aiLabel:'NOZA PARA EQUIPES',aiLimit:'Capacidade personalizada',features:['Gestão de usuários e equipes','Reuniões NOZA ilimitadas','Franquia de análise personalizada','Visão consolidada de performance','Human Pro para desenvolvimento individual','Memória longitudinal por usuário','Indicadores e evolução da equipe','Administração centralizada','Histórico e análises compartilhadas','Capacidade ampliada de processamento','Onboarding para equipes','Suporte prioritário'],cta:'CONHECER BUSINESS',note:'Plano dimensionado de acordo com o número de usuários e a capacidade de análise necessária.',Icon:Building2}
];
const money=(value:number)=>value.toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2});
export default function PlanosPage(){const[billing,setBilling]=useState<'monthly'|'annual'>('annual');const[busy,setBusy]=useState('');const subscribe=async(plan:string)=>{setBusy(plan);try{const r=await fetch('/api/billing/subscribe',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({plan})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Não foi possível iniciar a assinatura.');if(d.url)location.href=d.url}catch(e:any){alert(e.message)}finally{setBusy('')}};return <><AppSidebar/><AppTopbar floating/><main className="pricing-page"><section className="pricing-shell"><div className="pricing-kicker">PLANOS E PREÇOS</div><div className="billing-toggle" role="group" aria-label="Período de cobrança"><button className={billing==='monthly'?'active':''} onClick={()=>setBilling('monthly')}>Mensal 6 meses</button><button className={billing==='annual'?'active':''} onClick={()=>setBilling('annual')}>Anual <span>-20%</span></button></div><div className="pricing-grid">{plans.map(({key,name,eyebrow,monthly,description,aiLabel,aiLimit,features,cta,note,Icon,featured})=>{const value=monthly===null?null:(billing==='annual'?monthly*.8:monthly);return <article key={key} className={`price-card ${featured?'featured':''}`}><div className="price-card-top"><div className="plan-icon"><Icon/></div>{featured&&<span className="choice-badge">MAIS ESCOLHIDO</span>}</div><div className="plan-eyebrow">{eyebrow}</div><h2>{name}</h2><div className="plan-price">{value===null?null:<><span>R$</span> {money(value)}</>}</div>{monthly!==null&&billing==='annual'&&<div className="monthly-reference">R$ {money(monthly)} / mês</div>}<div className="ai-allowance"><div className="ai-allowance-head"><Sparkles/><span>{aiLabel}</span></div><strong>{aiLimit}</strong></div><div className="plan-divider"/><ul>{features.map(feature=><li key={feature}><span className="check"><Check/></span>{feature}</li>)}</ul><div className="plan-card-footer"><button className="plan-cta" disabled={!!busy} onClick={()=>key==='business'?location.href='/suporte':subscribe(key)}>{busy===key?'ABRINDO MERCADO PAGO...':cta}</button><p className="plan-note">{note}</p></div></article>})}</div><div className="pricing-footnote"><strong>CAPACIDADE DE ANÁLISE</strong><span>Reuniões continuam disponíveis mesmo ao atingir sua franquia. Você será avisado ao utilizar 80%, verá o tempo restante do ciclo e poderá adicionar horas ou migrar de plano sem interromper suas reuniões.</span></div></section></main></>}

/* production deployment */
