'use client';
import AppSidebar from '../AppSidebar';
import {useCallback,useEffect,useMemo,useState} from 'react';
import type {CSSProperties,FormEvent} from 'react';
import {ArrowRight,Bell,CalendarDays,ChevronLeft,ChevronRight,Clock,Mail,MapPin,Plus,Search,Trash2,Users,X} from 'lucide-react';
import './agenda.css';

type Guest={name?:string;email:string;avatarUrl?:string};
type Meeting={id:string;subject:string;starts_at:string|null;analysis:Record<string,unknown>|null};
type Form={subject:string;date:string;start:string;end:string;guests:string;objective:string;location:string};
const HOUR0=4, HOUR1=24, HOUR_HEIGHT=68;
const meta=(m:Meeting)=>m.analysis&&typeof m.analysis==='object'?m.analysis:{};
const cancelled=(m:Meeting)=>meta(m).agendaStatus==='cancelled';
const startAt=(m:Meeting)=>new Date(m.starts_at||Date.now());
const endAt=(m:Meeting)=>typeof meta(m).agendaEndsAt==='string'?new Date(String(meta(m).agendaEndsAt)):new Date(startAt(m).getTime()+45*60000);
const dateKey=(d:Date)=>d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');
const shift=(d:Date,n:number)=>{const r=new Date(d);r.setDate(r.getDate()+n);return r};
const monday=(d:Date)=>{const r=new Date(d);r.setHours(0,0,0,0);r.setDate(r.getDate()-((r.getDay()+6)%7));return r};
const fmtTime=(d:Date)=>new Intl.DateTimeFormat('pt-BR',{hour:'2-digit',minute:'2-digit',hourCycle:'h23',timeZone:'America/Sao_Paulo'}).format(d);
const fmtDay=(d:Date,o:Intl.DateTimeFormatOptions={weekday:'short',day:'2-digit'})=>new Intl.DateTimeFormat('pt-BR',{...o,timeZone:'America/Sao_Paulo'}).format(d).replace('.','');
const inputDate=(d:Date)=>{const x=new Date(d.getTime()-d.getTimezoneOffset()*60000);return x.toISOString().slice(0,16)};
const defaultForm=():Form=>{const s=new Date();s.setMinutes(Math.ceil(s.getMinutes()/30)*30,0,0);s.setHours(s.getHours()+1);const e=new Date(s.getTime()+45*60000);return{subject:'',date:inputDate(s).slice(0,10),start:inputDate(s).slice(11,16),end:inputDate(e).slice(11,16),guests:'',objective:'',location:''}};
function guests(m:Meeting):Guest[]{const v=Array.isArray(meta(m).agendaGuests)?meta(m).agendaGuests:Array.isArray(meta(m).participants)?meta(m).participants:[];return v.filter((x:any)=>x&&typeof x==='object').map((x:any)=>({name:typeof x.name==='string'?x.name:undefined,email:typeof x.email==='string'?x.email:'',avatarUrl:typeof (x.avatarUrl||x.avatar_url||x.photoUrl||x.photo||x.image)==='string'?String(x.avatarUrl||x.avatar_url||x.photoUrl||x.photo||x.image):undefined})).filter((x:Guest)=>x.email||x.name)}
function parseGuests(s:string):Guest[]{return s.split(/[\n,;]+/).map(x=>x.trim()).filter(Boolean).map(x=>{const m=x.match(/^(.*?)\s*<([^<>]+)>$/);return m?{name:m[1].trim()||undefined,email:m[2].trim().toLowerCase()}:{email:x.toLowerCase()}})}
function position(m:Meeting):CSSProperties{const s=startAt(m),e=endAt(m);const top=Math.max(0,(s.getHours()*60+s.getMinutes()-HOUR0*60)/60*HOUR_HEIGHT);const height=Math.max(45,Math.min((HOUR1-HOUR0)*HOUR_HEIGHT,top+(e.getTime()-s.getTime())/60000/60*HOUR_HEIGHT)-top-3);return{top:top+'px',height:height+'px'}}
function notifyText(delivery:any,label:string){if(!delivery)return label+' salvo.';if(!delivery.total)return label+' salvo; não há convidados com e-mail.';if(!delivery.configured)return label+' salvo. Os convites não foram enviados: o serviço de e-mail da NOZA não está configurado.';if(delivery.failed)return label+' enviado a '+delivery.sent+' de '+delivery.total+' convidados; houve falhas.';return label+' enviado a '+delivery.sent+' convidado(s).'}

export default function AgendaPage(){
 const [items,setItems]=useState<Meeting[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [cursor,setCursor]=useState(new Date()),[view,setView]=useState<'week'|'month'>('week'),[filter,setFilter]=useState<'active'|'all'|'cancelled'>('active'),[search,setSearch]=useState('');
 const [formOpen,setFormOpen]=useState(false),[form,setForm]=useState<Form>(defaultForm()),[editing,setEditing]=useState<string|null>(null),[selected,setSelected]=useState<Meeting|null>(null),[confirmCancel,setConfirmCancel]=useState(false),[guestInput,setGuestInput]=useState(''),[guestEditor,setGuestEditor]=useState(false);
 const [now,setNow]=useState(new Date()),[mounted,setMounted]=useState(false);
 const load=useCallback(async()=>{setError('');try{const r=await fetch('/api/agenda',{cache:'no-store'}),b=await r.json();if(!r.ok)throw Error(b.error||'Não foi possível carregar a agenda.');setItems(Array.isArray(b.meetings)?b.meetings:[])}catch(e){setError(e instanceof Error?e.message:'Erro ao conectar.')}finally{setLoading(false)}},[]);
 useEffect(()=>{setMounted(true);void load();const t=setInterval(()=>setNow(new Date()),60000);return()=>clearInterval(t)},[load]);
 const filtered=useMemo(()=>items.filter(m=>{if(filter==='active'&&cancelled(m))return false;if(filter==='cancelled'&&!cancelled(m))return false;const q=search.trim().toLowerCase();return!q||(m.subject+' '+guests(m).map(g=>g.name+' '+g.email).join(' ')).toLowerCase().includes(q)}).sort((a,b)=>startAt(a).getTime()-startAt(b).getTime()),[items,filter,search]);
 const week=monday(cursor),days=Array.from({length:7},(_,i)=>shift(week,i)),hours=Array.from({length:HOUR1-HOUR0},(_,i)=>HOUR0+i);

 const edit=(m:Meeting)=>{const s=startAt(m),e=endAt(m);setForm({...defaultForm(),subject:m.subject,date:dateKey(s),start:fmtTime(s),end:fmtTime(e)});setEditing(m.id);setSelected(null);setNotice('');setFormOpen(true)};
 const save=async(e:FormEvent)=>{e.preventDefault();const target=items.find(m=>m.id===editing);if(!target||busy)return;const s=new Date(form.date+'T'+form.start),en=new Date(form.date+'T'+form.end);if(!Number.isFinite(s.getTime())||!Number.isFinite(en.getTime())||en<=s){setNotice('Confira a nova data e os horários.');return}setBusy(true);try{const r=await fetch('/api/agenda/'+encodeURIComponent(target.id),{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({action:'reschedule',startsAt:s.toISOString(),endsAt:en.toISOString()})}),b=await r.json();if(!r.ok)throw Error(b.error||'Não foi possível adiar a reunião.');setFormOpen(false);setSelected(b.meeting);setNotice(notifyText(b.delivery,'Adiamento'));await load()}catch(e){setNotice(e instanceof Error?e.message:'Falha ao adiar.')}finally{setBusy(false)}};
 const cancel=async()=>{if(!selected||busy)return;setBusy(true);try{const r=await fetch('/api/agenda/'+encodeURIComponent(selected.id),{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({action:'cancel'})}),b=await r.json();if(!r.ok)throw Error(b.error||'Não foi possível cancelar.');setItems(v=>v.map(x=>x.id===b.meeting.id?b.meeting:x));setSelected(b.meeting);setConfirmCancel(false);setNotice(notifyText(b.delivery,'Cancelamento'))}catch(e){setNotice(e instanceof Error?e.message:'Falha ao cancelar.')}finally{setBusy(false)}};
 const addGuest=async()=>{if(!selected||busy)return;const people=parseGuests(guestInput);if(!people.length||people.length>1||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(people[0].email)){setNotice('Informe um participante com e-mail válido.');return}setBusy(true);try{const r=await fetch('/api/agenda/'+encodeURIComponent(selected.id),{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({action:'addGuest',guests:people})}),b=await r.json();if(!r.ok)throw Error(b.error||'Não foi possível adicionar participante.');setItems(v=>v.map(x=>x.id===b.meeting.id?b.meeting:x));setSelected(b.meeting);setGuestInput('');setGuestEditor(false);setNotice(notifyText(b.delivery,'Convite'))}catch(e){setNotice(e instanceof Error?e.message:'Falha ao adicionar participante.')}finally{setBusy(false)}};
 const step=(n:number)=>setCursor(d=>view==='week'?shift(d,n*7):new Date(d.getFullYear(),d.getMonth()+n,1));
 const thisWeek=days.some(d=>dateKey(d)===dateKey(now)),nowTop=(now.getHours()*60+now.getMinutes()-HOUR0*60)/60*HOUR_HEIGHT;
 const dayItems=(d:Date)=>filtered.filter(m=>(filter!=='active'||!cancelled(m))&&dateKey(startAt(m))===dateKey(d)&&startAt(m).getHours()>=HOUR0&&startAt(m).getHours()<HOUR1);
 const monthCells=()=>{const first=new Date(cursor.getFullYear(),cursor.getMonth(),1);return Array.from({length:42},(_,i)=>shift(monday(first),i))};
 const open=(m:Meeting)=>{setSelected(m);setConfirmCancel(false);setNotice('')};
 const selectedCancelled=selected?cancelled(selected):false;
 return <main className="app-shell agenda-page"><AppSidebar/><section className="agenda-content"><div className="agenda-shell">
  <header className="agenda-header"><div><span className="agenda-eyebrow">NOZA · PERFORMANCE INTELLIGENCE</span><h1>Agenda de reuniões</h1><p>Visualize, adie ou cancele seus encontros.</p></div></header>
  {notice&&<div className="agenda-notice" role="status"><Bell/><span>{notice}</span><button onClick={()=>setNotice('')} aria-label="Fechar"><X/></button></div>}
  {error&&<div className="agenda-error" role="alert">{error}<button onClick={()=>{setLoading(true);void load()}}>Tentar novamente</button></div>}
  <div className="agenda-toolbar"><div className="agenda-period"><button className="agenda-today" onClick={()=>setCursor(new Date())}>Hoje</button><button aria-label="Anterior" onClick={()=>step(-1)}><ChevronLeft/></button><button aria-label="Próximo" onClick={()=>step(1)}><ChevronRight/></button><strong>{mounted?(view==='week'?fmtDay(week,{day:'numeric',month:'short'})+' – '+fmtDay(shift(week,6),{day:'numeric',month:'short'}):new Intl.DateTimeFormat('pt-BR',{month:'long',year:'numeric'}).format(cursor)):''}</strong></div><div className="agenda-tools"><label className="agenda-search"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar reunião"/></label><div className="agenda-toggle"><button className={view==='week'?'on':''} onClick={()=>setView('week')}>Semana</button><button className={view==='month'?'on':''} onClick={()=>setView('month')}>Mês</button></div></div></div>
  <div className="agenda-filter"><div>{[['active','Agendadas'],['all','Todas'],['cancelled','Canceladas']].map(x=><button key={x[0]} className={filter===x[0]?'on':''} onClick={()=>setFilter(x[0] as any)}>{x[1]}</button>)}</div><span>{filtered.length} reunião(ões)</span></div>
  {loading?<div className={"agenda-loading "+view} role="status">Carregando agenda…</div>:view==='week'?<section className="agenda-week"><div className="agenda-week-head"><div/>{days.map(d=><button key={dateKey(d)} className={dateKey(d)===dateKey(now)?'today':''} ><small>{fmtDay(d,{weekday:'short'}).toUpperCase()}</small><strong>{String(d.getDate()).padStart(2,'0')}</strong></button>)}</div><div className="agenda-week-body"><div className="agenda-hours">{hours.map(h=><span key={h}>{String(h).padStart(2,'0')}:00</span>)}<span className="agenda-hour-half" style={{top:(HOUR1-HOUR0-.5)*HOUR_HEIGHT+'px'}}>23:30</span></div>{days.map(d=><div className={'agenda-day '+(dateKey(d)===dateKey(now)?'today':'')} key={dateKey(d)}>{thisWeek&&dateKey(d)===dateKey(now)&&now.getHours()>=HOUR0&&now.getHours()<HOUR1&&<i className="agenda-now" style={{top:nowTop+'px'}}/>}{dayItems(d).map(m=><button key={m.id} className={'agenda-event '+(cancelled(m)?'cancelled':'')} style={position(m)} onClick={()=>open(m)}><strong>{m.subject}</strong><span>{fmtTime(startAt(m))}–{fmtTime(endAt(m))}</span>{!cancelled(m)&&guests(m).length>0&&<span className="agenda-avatar-stack" title="Abra para ver ou adicionar participantes">{guests(m).slice(0,2).map((g,i)=><i className="agenda-avatar-mini" key={g.email||i}>{g.avatarUrl?<img src={g.avatarUrl} alt=""/>:(g.name||g.email||'?').slice(0,1).toUpperCase()}</i>)}{guests(m).length>2&&<i className="agenda-avatar-more">+{guests(m).length-2}</i>}</span>}</button>)}</div>)}</div></section>:<section className="agenda-month"><div className="agenda-weekdays">{['Seg','Ter','Qua','Qui','Sex','Sáb','Dom'].map(d=><span key={d}>{d}</span>)}</div><div className="agenda-month-grid">{monthCells().map(d=>{const list=filtered.filter(m=>dateKey(startAt(m))===dateKey(d));return <button key={dateKey(d)} className={'agenda-month-cell '+(d.getMonth()!==cursor.getMonth()?'muted ':'')+(dateKey(d)===dateKey(now)?'today':'')} onClick={()=>{setCursor(d);setView('week')}}><span>{d.getDate()}</span>{list.slice(0,3).map(m=><i className={cancelled(m)?'cancelled':''} key={m.id} onClick={e=>{e.stopPropagation();open(m)}}>{fmtTime(startAt(m))} {m.subject}</i>)}</button>})}</div></section>}
  <section className="agenda-next"><div className="agenda-section-heading"><div><span>VISÃO RÁPIDA</span><h2>Próximas reuniões</h2></div><button onClick={()=>{setCursor(new Date());setView('week')}}>Esta semana <ArrowRight/></button></div>{filtered.filter(m=>!cancelled(m)&&startAt(m).getTime()>=new Date(new Date().setHours(0,0,0,0)).getTime()).slice(0,4).map(m=><button className="agenda-next-card" key={m.id} onClick={()=>open(m)}><time>{fmtDay(startAt(m),{day:'2-digit',month:'short'})}</time><span><strong>{m.subject}</strong><small><Clock/>{fmtTime(startAt(m))}–{fmtTime(endAt(m))}<i>·</i><span className="agenda-avatar-stack" title="Abra para ver ou adicionar participantes">{guests(m).slice(0,3).map((g,i)=><i className="agenda-avatar-mini" key={g.email||i}>{g.avatarUrl?<img src={g.avatarUrl} alt=""/>:(g.name||g.email||'?').slice(0,1).toUpperCase()}</i>)}{guests(m).length>3&&<i className="agenda-avatar-more">+{guests(m).length-3}</i>}<i className="agenda-avatar-add">+</i></span></small></span><span className="agenda-status"><i/>{startAt(m).getTime()<Date.now()?'Concluída':'Confirmada'}</span><ChevronRight/></button>)}{!filtered.some(m=>!cancelled(m)&&startAt(m).getTime()>=new Date(new Date().setHours(0,0,0,0)).getTime())&&<div className="agenda-empty"><CalendarDays/><span><b>Você não tem reuniões futuras.</b><small>Quando novas reuniões forem agendadas, elas aparecerão aqui.</small></span></div>}</section>
 </div></section>
 {formOpen&&<div className="agenda-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setFormOpen(false)}}><section className="agenda-modal" role="dialog" aria-modal="true" aria-labelledby="agenda-form-title"><header><div><span>ADIAR REUNIÃO</span><h2 id="agenda-form-title">Escolher novo horário</h2></div><button onClick={()=>setFormOpen(false)} aria-label="Fechar"><X/></button></header><form onSubmit={save}><p className="agenda-reschedule-subject">{form.subject}</p><div className="agenda-form-grid"><label>Nova data<input type="date" autoFocus value={form.date} onChange={e=>setForm({...form,date:e.target.value})} required/></label><label>Início<input type="time" value={form.start} onChange={e=>setForm({...form,start:e.target.value})} required/></label><label>Término<input type="time" value={form.end} onChange={e=>setForm({...form,end:e.target.value})} required/></label></div>{notice&&<p className="agenda-form-error">{notice}</p>}<footer><button type="button" className="agenda-secondary" onClick={()=>setFormOpen(false)}>Voltar</button><button type="submit" className="agenda-primary" disabled={busy}>{busy?'Adiar…':'Confirmar novo horário'}</button></footer></form></section></div>}
 {selected&&<div className="agenda-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget){setSelected(null);setConfirmCancel(false)}}}><section className="agenda-modal" role="dialog" aria-modal="true" aria-labelledby="agenda-detail-title"><header><div><span>DETALHES DA REUNIÃO</span><h2 id="agenda-detail-title">{selected.subject}</h2></div><button onClick={()=>setSelected(null)} aria-label="Fechar"><X/></button></header><div className="agenda-meta"><span><CalendarDays/>{fmtDay(startAt(selected),{weekday:'long',day:'numeric',month:'long',year:'numeric'})}</span><span><Clock/>{fmtTime(startAt(selected))} – {fmtTime(endAt(selected))}</span><span className={selectedCancelled?'cancelled':''}><i/>{selectedCancelled?'Cancelada':selectedPast?'Concluída':'Confirmada'}</span></div>{typeof meta(selected).agendaObjective==='string'&&<div className="agenda-info"><small>OBJETIVO</small><p>{meta(selected).agendaObjective}</p></div>}{typeof meta(selected).agendaLocation==='string'&&<div className="agenda-info"><small>LOCAL / LINK</small><p><MapPin/>{meta(selected).agendaLocation}</p></div>}<div className="agenda-info"><small>PARTICIPANTES · {guests(selected).length}</small>{guests(selected).length?guests(selected).map((g,i)=><p className="agenda-guest" key={g.email||i}>{g.avatarUrl?<img className="agenda-avatar-img" src={g.avatarUrl} alt=""/>:<span>{(g.name||g.email||'?').slice(0,1).toUpperCase()}</span>}{g.name&&<b>{g.name}</b>}<small><Mail/>{g.email||'Sem e-mail'}</small></p>):<p>Nenhum convidado adicionado.</p>}</div>{!selectedCancelled&&<div className="agenda-add-guest">{guestEditor?<><label>Adicionar participante<input value={guestInput} onChange={e=>setGuestInput(e.target.value)} placeholder="Nome <email@empresa.com>" autoFocus/></label><button disabled={busy} onClick={()=>void addGuest()}>Adicionar</button><button className="quiet" onClick={()=>{setGuestEditor(false);setGuestInput('')}}>Cancelar</button></>:<button onClick={()=>setGuestEditor(true)}><Plus/>Adicionar participante</button>}</div>}{selectedCancelled&&<p className="agenda-cancelled-note"><Bell/>Cancelamento registrado no histórico.</p>}{confirmCancel&&!selectedCancelled&&<div className="agenda-confirm"><b>Cancelar esta reunião?</b><p>O status será atualizado e os convidados receberão um aviso quando o envio por e-mail estiver configurado.</p><footer><button onClick={()=>setConfirmCancel(false)}>Voltar</button><button className="danger" disabled={busy} onClick={()=>void cancel()}>{busy?'Cancelando…':'Confirmar cancelamento'}</button></footer></div>}{!selectedCancelled&&<footer className="agenda-actions"><button onClick={()=>edit(selected)}><Clock/>Adiar reunião</button><button className="danger" onClick={()=>setConfirmCancel(true)}><Trash2/>Cancelar reunião</button></footer>}</section></div>}
 </main>
}
