'use client';
import {useEffect,useMemo,useState} from 'react';
import AppSidebar from '../AppSidebar';
import './calibragem.css';

const qs=[
 {tag:'DESCOBERTA',q:'Um cliente diz: “Gostei, mas neste momento está muito caro.” Qual é seu primeiro movimento?',a:['Defendo o retorno do investimento.','Investigo o critério usado para definir “caro”.','Crio urgência para evitar adiamento.','Apresento uma condição melhor.'],skill:'Investigação',w:[58,94,68,52]},
 {tag:'ESCUTA',q:'A pessoa diz que preço não é o problema, mas demonstra hesitação ao falar da implementação. O que você considera mais provável?',a:['Ela está escondendo uma objeção financeira.','Existe um risco percebido que ainda não foi nomeado.','Ela precisa de mais benefícios para decidir.','A hesitação indica falta de interesse.'],skill:'Escuta',w:[54,95,61,42]},
 {tag:'REFLEXÃO',q:'Você tem uma resposta que parece obviamente correta em poucos segundos. Em uma decisão importante, o que faz?',a:['Confio na primeira leitura se tenho experiência.','Procuro deliberadamente uma hipótese que tornaria minha leitura errada.','Peço validação de alguém antes de pensar mais.','Adio para evitar viés.'],skill:'Decisão',w:[64,96,70,55]},
 {tag:'ARGUMENTAÇÃO',q:'Duas evidências sustentam sua tese, mas uma terceira evidência forte a contradiz. Como você constrói a recomendação?',a:['Priorizo as duas evidências convergentes.','Exponho a contradição e recalibro o grau de confiança.','Retiro a evidência contraditória por ser exceção.','Evito recomendar até existir consenso.'],skill:'Argumentação',w:[48,97,30,66]},
 {tag:'PERSUASÃO',q:'Uma pessoa inteligente discorda de você mesmo após compreender perfeitamente seus argumentos. Qual hipótese você testa primeiro?',a:['Ela não percebeu o peso das evidências.','Os critérios de decisão dela podem ser diferentes dos meus.','Ela está defendendo o próprio ego.','Falta uma autoridade externa validar meu ponto.'],skill:'Persuasão',w:[58,96,38,55]},
 {tag:'NEGOCIAÇÃO',q:'Você recebe uma proposta boa, mas com prazo artificialmente curto. Qual é a resposta cognitivamente mais segura?',a:['Decido rápido para não perder a oportunidade.','Separo valor da proposta da pressão temporal e avalio cada um.','Rejeito porque urgência é manipulação.','Peço mais prazo e só avalio depois.'],skill:'Negociação',w:[40,97,61,78]},
 {tag:'COMUNICAÇÃO',q:'Você precisa explicar uma ideia complexa a alguém que conhece pouco do assunto. Como verifica se houve compreensão real?',a:['Pergunto se a pessoa entendeu.','Peço que ela reconstrua a ideia com as próprias palavras.','Repito a ideia de forma mais simples.','Envio um resumo depois.'],skill:'Comunicação',w:[55,97,75,48]},
 {tag:'CONDUÇÃO',q:'Uma conversa importante está produtiva, mas começa a abrir três caminhos diferentes. O que você faz?',a:['Exploro todos para não perder informação.','Nomeio os caminhos, priorizo um e estaciono os demais.','Escolho silenciosamente o que considero melhor.','Volto imediatamente à pauta original.'],skill:'Condução',w:[59,96,63,72]},
 {tag:'METACOGNIÇÃO',q:'Depois de uma decisão que deu certo, qual pergunta produz mais aprendizado?',a:['O que fiz certo?','Meu processo foi bom ou apenas tive um resultado favorável?','Como repetir exatamente a mesma estratégia?','Quem contribuiu para o resultado?'],skill:'Decisão',w:[72,98,55,62]},
 {tag:'INVESTIGAÇÃO',q:'O cliente pede uma funcionalidade específica. Antes de discutir se ela existe, qual pergunta gera mais informação?',a:['Quanto você pagaria por ela?','O que aconteceria no seu processo se essa funcionalidade não existisse?','Qual concorrente oferece isso?','Quantas pessoas usariam?'],skill:'Investigação',w:[62,97,66,76]},
 {tag:'AMBIGUIDADE',q:'Você recebe dados incompletos e precisa recomendar um caminho hoje. Qual abordagem é mais robusta?',a:['Escolho a opção com maior potencial.','Declaro premissas, incertezas e o que faria minha recomendação mudar.','Espero até ter todos os dados.','Uso minha experiência para preencher as lacunas.'],skill:'Argumentação',w:[63,98,54,67]},
 {tag:'ESCUTA',q:'Alguém responde “faz sentido” após sua apresentação. O que essa frase prova?',a:['Que a pessoa concordou.','Que houve compreensão suficiente para avançar.','Quase nada sobre intenção; preciso testar significado e compromisso.','Que a objeção principal foi resolvida.'],skill:'Escuta',w:[38,66,98,52]},
 {tag:'INFLUÊNCIA',q:'Qual movimento tende a preservar mais autonomia da outra pessoa durante uma tentativa de influência?',a:['Mostrar somente a recomendação mais forte.','Explicitar critérios, alternativas e consequências para ela decidir.','Usar prova social para reduzir incerteza.','Criar contraste entre perda e ganho.'],skill:'Persuasão',w:[54,97,71,68]},
 {tag:'NEGOCIAÇÃO',q:'A outra parte faz uma concessão inesperadamente grande. Qual leitura você evita assumir?',a:['Que o acordo melhorou.','Que a concessão revela necessariamente o limite real dela.','Que existe informação nova.','Que vale investigar o motivo da concessão.'],skill:'Negociação',w:[61,97,72,88]},
 {tag:'COMUNICAÇÃO',q:'Uma explicação tecnicamente correta não produziu mudança de entendimento. Qual ajuste vem primeiro?',a:['Adicionar mais evidências.','Diagnosticar onde o modelo mental da pessoa diverge do seu.','Simplificar todas as palavras.','Usar uma história emocional.'],skill:'Comunicação',w:[57,98,74,65]},
 {tag:'DECISÃO',q:'Você investiu muito tempo em um projeto que agora apresenta sinais ruins. O investimento passado deve pesar quanto na decisão de continuar?',a:['Muito, porque abandonar desperdiça o esforço.','Somente se aumentar a probabilidade de sucesso futuro.','Nada; avalio custos e benefícios futuros, separando o que já é irrecuperável.','Depende de quanto falta para terminar.'],skill:'Decisão',w:[30,72,98,55]},
 {tag:'CONDUÇÃO',q:'Em uma reunião, duas pessoas discutem soluções antes de concordarem sobre o problema. Sua intervenção é:',a:['Escolher a solução mais plausível.','Fazer cada uma defender sua solução.','Reconstruir primeiro o problema, critérios e evidências compartilhadas.','Deixar o conflito revelar a melhor alternativa.'],skill:'Condução',w:[48,57,98,62]},
 {tag:'ARGUMENTAÇÃO',q:'Qual evidência deveria mudar mais sua confiança numa hipótese?',a:['Uma opinião forte de especialista.','Um dado que você já esperava encontrar.','Uma observação improvável caso sua hipótese estivesse errada.','Muitos exemplos coerentes com sua experiência.'],skill:'Argumentação',w:[67,58,98,62]},
 {tag:'INVESTIGAÇÃO',q:'Uma pessoa diz “preciso pensar”. Qual pergunta evita pressionar e aumenta diagnóstico?',a:['Pensar exatamente sobre o quê?','O que falta estar claro para você conseguir avaliar com segurança?','Quando posso te cobrar uma resposta?','Existe alguém impedindo a decisão?'],skill:'Investigação',w:[82,98,35,58]},
 {tag:'ESCUTA',q:'A fala diz “está tudo certo”, mas contexto, pausas e comportamento apontam desconforto. O que você faz?',a:['Confio na declaração explícita.','Assumo que existe uma objeção escondida.','Aponto a discrepância com neutralidade e convido a pessoa a esclarecer.','Ignoro sinais não verbais porque são subjetivos.'],skill:'Escuta',w:[55,62,98,50]},
 {tag:'PERSUASÃO',q:'Você descobre que sua solução não é a melhor para a prioridade atual do cliente. Qual movimento preserva mais influência no longo prazo?',a:['Reposicionar a prioridade para favorecer sua solução.','Dizer isso claramente e recomendar o próximo passo mais coerente, mesmo sem venda.','Reduzir preço para compensar.','Destacar benefícios secundários.'],skill:'Persuasão',w:[35,99,45,57]},
 {tag:'NEGOCIAÇÃO',q:'Quando a negociação entra em impasse, qual pergunta tende a revelar espaço de criação de valor?',a:['Qual é seu preço final?','Quais condições têm valores diferentes para cada lado?','Quem tem autoridade para ceder?','Você realmente quer fechar?'],skill:'Negociação',w:[52,98,61,45]},
 {tag:'COMUNICAÇÃO',q:'Você tem 45 segundos para comunicar uma recomendação complexa a um decisor. O que prioriza?',a:['Contexto completo para evitar simplificação.','Conclusão, razão decisiva, evidência crítica e próximo passo.','Somente a conclusão.','Uma história memorável.'],skill:'Comunicação',w:[50,98,69,65]},
 {tag:'CONDUÇÃO',q:'O grupo concorda rapidamente com sua primeira ideia. Qual ação melhora a qualidade da decisão?',a:['Avançar enquanto existe alinhamento.','Pedir que alguém formule o melhor argumento contra a opção escolhida.','Fazer uma votação para confirmar.','Adicionar mais benefícios da ideia.'],skill:'Condução',w:[55,99,67,42]},
 {tag:'METACOGNIÇÃO',q:'Ao perceber que mudou de opinião, qual sinal indica raciocínio mais maduro?',a:['Conseguir defender a nova opinião com convicção.','Identificar qual evidência mudou seu modelo e o que ainda poderia fazê-lo mudar novamente.','Esquecer a posição anterior para evitar inconsistência.','Encontrar pessoas que agora concordam com você.'],skill:'Decisão',w:[63,99,31,42]},
 {tag:'JULGAMENTO',q:'Um profissional excelente falhou duas vezes seguidas. Qual conclusão é mais defensável com esses dados?',a:['Ele perdeu performance.','As falhas provam um novo padrão.','Duas ocorrências são insuficientes; investigo taxa-base, contexto e processo.','Ele provavelmente está sob pressão.'],skill:'Argumentação',w:[42,35,99,50]},
 {tag:'INVESTIGAÇÃO',q:'Qual pergunta distingue melhor sintoma de causa?',a:['Por que isso aconteceu?','O que mudou imediatamente antes do problema aparecer e em quais condições ele não aparece?','Quem percebeu primeiro?','Há quanto tempo isso incomoda?'],skill:'Investigação',w:[72,99,58,63]},
 {tag:'ESCUTA',q:'Você acredita ter entendido a motivação da pessoa. Qual movimento reduz erro de interpretação?',a:['Usar a motivação no seu argumento.','Formular sua hipótese como hipótese e pedir correção.','Fazer outra pergunta sem revelar sua leitura.','Esperar a pessoa repetir espontaneamente.'],skill:'Escuta',w:[62,99,77,54]},
 {tag:'NEGOCIAÇÃO',q:'Você pode ganhar mais agora explorando uma assimetria de informação que a outra parte desconhece. O que avalia além do ganho imediato?',a:['Somente se é legal.','Confiança, reciprocidade, reputação e valor da relação futura.','Se a outra parte faria o mesmo.','A chance de ela descobrir.'],skill:'Negociação',w:[58,99,49,37]},
 {tag:'SÍNTESE',q:'Depois de analisar informações conflitantes, qual saída demonstra maior qualidade de pensamento?',a:['Uma resposta firme para transmitir segurança.','Uma conclusão proporcional à evidência, com confiança explícita e condições de revisão.','Uma lista de todas as possibilidades sem escolher.','A alternativa apoiada pela maioria.'],skill:'Comunicação',w:[48,99,69,52]},
 {tag:'PERSUASÃO',q:'Quando alguém resiste a uma mudança, qual diagnóstico vem antes da tentativa de convencer?',a:['Quanto poder de decisão ela possui.','Se a resistência vem de valor, risco, identidade, custo, incerteza ou perda percebida.','Qual argumento costuma funcionar com pessoas parecidas.','Quanto tempo tenho para persuadir.'],skill:'Persuasão',w:[61,99,55,50]},
 {tag:'CONDUÇÃO',q:'Você percebe que a conversa está avançando com uma premissa nunca verificada. O que faz?',a:['Mantenho o ritmo e verifico depois.','Interrompo de forma objetiva, torno a premissa explícita e testo sua validade.','Procuro sinais de que alguém discorda.','Assumo que o consenso valida a premissa.'],skill:'Condução',w:[38,99,68,34]}
];
const skills=['Comunicação','Escuta','Investigação','Persuasão','Argumentação','Negociação','Condução','Decisão'];

export default function Calibragem(){
 const [started,setStarted]=useState(false),[i,setI]=useState(0),[answers,setAnswers]=useState<number[]>([]);
 const done=answers.length===qs.length;
 const [saved,setSaved]=useState(false);
 const scores=useMemo(()=>Object.fromEntries(skills.map(s=>{const items=qs.map((q,idx)=>({q,idx})).filter(x=>x.q.skill===s&&answers[x.idx]!==undefined);if(!items.length)return[s,0];const raw=items.reduce((sum,x)=>sum+x.q.w[answers[x.idx]],0)/items.length;return[s,Math.round(raw)]})),[answers]);
 const choose=(n:number)=>{const next=[...answers,n];setAnswers(next);if(i<qs.length-1)setTimeout(()=>setI(i+1),120)};
 const performance=Math.round(Object.values(scores).reduce((a:number,b:any)=>a+Number(b),0)/skills.length)||0;
 useEffect(()=>{if(!done||saved)return;const payload={performance,scores,completedAt:new Date().toISOString()};localStorage.setItem('noza-performance-baseline',JSON.stringify(payload));window.dispatchEvent(new CustomEvent('noza:performance-updated',{detail:payload}));setSaved(true)},[done,saved,performance,scores]);
 const reset=()=>{localStorage.removeItem('noza-performance-baseline');window.dispatchEvent(new Event('noza:performance-reset'));setAnswers([]);setI(0);setSaved(false);setStarted(false)};
 return <div className="cal-shell"><AppSidebar/><main className="cal-main">
   <div className="cal-top"><span>NOZA / INTELLIGENCE SYSTEM</span><span>{started&&!done?String(i+1).padStart(2,'0')+' / '+String(qs.length).padStart(2,'0'):'BASELINE'}</span></div>
   {!started?<section className="cal-intro">
    <div className="cal-kicker"><i/> CALIBRAGEM INICIAL</div>
    <h1>Antes de evoluir sua performance,<br/><em>precisamos entender como você pensa.</em></h1>
    <p>A NOZA vai mapear como você interpreta situações, constrói argumentos, faz perguntas, influencia decisões e reage sob pressão.</p>
    <div className="cal-domains">{skills.map((s,n)=><span key={s}><b>0{n+1}</b>{s}</span>)}</div>
    <button className="cal-start" onClick={()=>setStarted(true)}>INICIAR CALIBRAGEM <b>→</b></button>
    <small>32 cenários · 8 dimensões · aproximadamente 15 minutos · respostas desenhadas para exigir julgamento</small>
   </section>:!done?<section className="cal-test">
    <div className="cal-progress"><i style={{width:`${((i+1)/qs.length)*100}%`}}/></div>
    <div className="cal-code">CENÁRIO {String(i+1).padStart(2,'0')} <span>— {qs[i].tag}</span></div>
    <h2>{qs[i].q}</h2>
    <p className="cal-hint">Escolha a resposta mais próxima do que você realmente faria — não do que parece ideal.</p>
    <div className="cal-options">{qs[i].a.map((a,n)=><button key={a} onClick={()=>choose(n)}><b>{String.fromCharCode(65+n)}</b><span>{a}</span><i>↗</i></button>)}</div>
   </section>:<section className="cal-result">
    <div className="cal-kicker"><i/> BASELINE 01 CONCLUÍDO</div>
    <h1>Seu número de performance<br/><em>foi identificado.</em></h1><div className="cal-performance-number"><strong>{performance}</strong><span>/100<br/>PERFORMANCE</span></div>
    <p>Este é um retrato inicial. A NOZA vai confrontar esta calibragem com evidências reais das suas próximas interações.</p>
    <div className="cal-scoregrid">{skills.map(s=><div key={s}><header><span>{s}</span><b>{scores[s]}</b></header><div><i style={{width:`${scores[s]}%`}}/></div></div>)}</div>
    <div className="cal-insight"><span>PRIORIDADE INICIAL</span><strong>Investigação antes da argumentação.</strong><p>Seu padrão sugere espaço para aprofundar contexto e critérios antes de construir a resposta. A confiança deste diagnóstico aumentará com evidências reais.</p></div>
    <button className="cal-start" onClick={reset}>RESETAR CALIBRAGEM <b>↻</b></button>
   </section>}
 </main></div>
}