'use client';
import {useEffect,useMemo,useState} from 'react';
import AppSidebar from '../AppSidebar';
import './calibragem.css';

const qs=[
{tag:'LEITURA DE INTENÇÃO',q:'Uma pessoa diz “vou pensar” logo depois de demonstrar entusiasmo. Qual é a leitura mais inteligente?',a:['Ela perdeu o interesse.','Ela quer encerrar a conversa.','Existe uma variável ainda não revelada; eu investigaria sem presumir qual.','Ela está esperando uma condição melhor.'],skill:'Leitura',w:[45,40,100,58]},
{tag:'ESCUTA',q:'Alguém diz “não é pelo dinheiro”, mas volta três vezes ao custo durante a conversa. O que você faz com essa contradição?',a:['Assumo que dinheiro é o verdadeiro problema.','Ignoro o custo porque a pessoa negou.','Trato como sinal relevante e exploro o significado que custo tem para ela.','Mostro imediatamente que o preço vale a pena.'],skill:'Leitura',w:[62,25,100,48]},
{tag:'EMPATIA COGNITIVA',q:'Uma pessoa reage de forma muito mais defensiva do que você esperava a uma crítica pequena. Antes de concluir que ela é “difícil”, qual hipótese é mais madura?',a:['Ela tem baixa inteligência emocional.','A crítica pode ter tocado em algo que representa ameaça, identidade ou histórico que eu desconheço.','Ela não sabe receber feedback.','Ela está tentando manipular a conversa.'],skill:'Psicologia',w:[35,100,45,32]},
{tag:'PERGUNTAS',q:'Você quer entender por que alguém não tomou uma decisão importante. Qual pergunta tende a revelar mais?',a:['Por que você ainda não decidiu?','O que precisaria estar diferente para essa decisão parecer segura para você?','Você realmente quer fazer isso?','Quem está impedindo você?'],skill:'Investigação',w:[65,100,45,38]},
{tag:'INFLUÊNCIA',q:'Você percebe que quanto mais explica sua ideia, mais a outra pessoa resiste. Qual é o próximo movimento mais inteligente?',a:['Explicar de forma mais simples.','Apresentar mais provas.','Parar de defender e investigar o que ela está tentando proteger ou evitar.','Usar um exemplo de alguém parecido com ela.'],skill:'Influência',w:[58,45,100,65]},
{tag:'CONTEXTO',q:'Uma pessoa normalmente comunicativa fica muito curta e objetiva numa conversa específica. O que isso significa?',a:['Ela está irritada.','Ela perdeu interesse.','É uma mudança de padrão; preciso de contexto antes de atribuir uma causa.','Ela está escondendo alguma coisa.'],skill:'Leitura',w:[35,42,100,40]},
{tag:'NEGOCIAÇÃO',q:'Alguém pede desconto imediatamente, antes mesmo de discutir detalhes. O pedido pode representar:',a:['Falta de dinheiro.','Uma técnica de negociação.','Teste de margem, hábito, percepção de risco, orçamento ou valor — ainda não há dados para escolher uma causa.','Falta de interesse real.'],skill:'Negociação',w:[42,68,100,30]},
{tag:'COMUNICAÇÃO',q:'Você explica algo e a pessoa responde “sim, entendi”, mas depois age como se tivesse entendido outra coisa. Qual falha é mais provável?',a:['Ela não prestou atenção.','Ela mentiu quando disse que entendeu.','Houve ilusão de compreensão; confirmar com reconstrução teria revelado a diferença.','A explicação precisava ser mais longa.'],skill:'Comunicação',w:[40,28,100,52]},
{tag:'EMOÇÃO',q:'Uma pessoa apresenta argumentos lógicos, mas você percebe que nenhum deles parece explicar a intensidade da resistência. O que você considera?',a:['Os argumentos são falsos.','Pode existir uma motivação emocional ou identitária não verbalizada por trás das justificativas.','Ela não é racional.','Preciso vencer cada argumento individualmente.'],skill:'Psicologia',w:[45,100,20,35]},
{tag:'CONFIANÇA',q:'Uma pessoa fala com enorme segurança sobre um assunto. O que a segurança da fala permite concluir?',a:['Que ela domina o assunto.','Que provavelmente está certa.','Que está confiante; competência e precisão precisam de evidências separadas.','Que possui experiência prática.'],skill:'Leitura',w:[25,35,100,45]},
{tag:'PERSPECTIVA',q:'Você considera uma decisão obviamente boa, mas outra pessoa inteligente a rejeita. Antes de persuadir, o que procura?',a:['Onde ela está errando.','Qual informação ela não entendeu.','Quais objetivos, riscos e critérios ela está usando que diferem dos meus.','Quem tem mais experiência.'],skill:'Psicologia',w:[25,48,100,40]},
{tag:'SILÊNCIO',q:'Depois de você fazer uma pergunta importante, a pessoa fica vários segundos em silêncio. Qual reação preserva mais informação?',a:['Reformular imediatamente a pergunta.','Preencher o silêncio para reduzir desconforto.','Dar espaço; o silêncio pode indicar processamento, conflito ou cuidado com a resposta.','Interpretar como resistência.'],skill:'Comunicação',w:[55,32,100,35]},
{tag:'CONTRADIÇÃO',q:'Uma pessoa afirma que determinada questão “não importa”, mas retorna espontaneamente a ela várias vezes. Como você lê isso?',a:['Ela está sendo incoerente.','Provavelmente importa de alguma forma, embora talvez nem ela tenha organizado isso claramente.','Ela está tentando confundir você.','Você deve confrontar a contradição diretamente.'],skill:'Leitura',w:[40,100,25,58]},
{tag:'OBJEÇÃO',q:'Alguém apresenta cinco razões diferentes para não avançar. Qual estratégia produz melhor diagnóstico?',a:['Responder às cinco.','Descobrir qual razão, se resolvida, realmente mudaria a decisão.','Começar pela mais fácil.','Mostrar que algumas razões se contradizem.'],skill:'Investigação',w:[48,100,52,58]},
{tag:'RAPPORT',q:'Qual comportamento demonstra conexão real melhor do que simplesmente imitar gestos e palavras?',a:['Usar o mesmo vocabulário.','Conseguir prever quais preocupações e critérios importam para aquela pessoa e adaptar a conversa a eles.','Manter contato visual constante.','Concordar com pontos pequenos antes de discordar.'],skill:'Psicologia',w:[48,100,35,55]},
{tag:'DECISÃO',q:'Uma pessoa pede mais informações repetidamente, embora já tenha dados suficientes para decidir. O que pode estar acontecendo?',a:['Ela é indecisa.','Ela precisa de uma apresentação melhor.','A busca por informação pode estar funcionando como proteção contra risco, responsabilidade ou arrependimento.','Ela quer adiar de propósito.'],skill:'Decisão',w:[35,45,100,52]},
{tag:'ESCUTA',q:'Durante uma conversa, alguém muda uma palavra: antes dizia “preço”, depois passa a dizer “risco”. Por que isso importa?',a:['Não importa; são palavras próximas.','Pode indicar que a representação mental do problema mudou e revelar a objeção mais profunda.','Significa que a pessoa está convencida.','É apenas escolha de vocabulário.'],skill:'Leitura',w:[20,100,40,30]},
{tag:'PRESSÃO',q:'Sob pressão, uma pessoa começa a responder muito rápido e interromper. Qual conclusão é mais segura?',a:['Ela está mentindo.','Ela ficou agressiva.','O padrão indica alteração de estado, mas a causa ainda precisa ser investigada.','Ela quer dominar você.'],skill:'Psicologia',w:[20,35,100,28]},
{tag:'INFLUÊNCIA',q:'Você quer mudar a opinião de alguém sem gerar resistência desnecessária. Qual caminho tende a ser cognitivamente mais forte?',a:['Apresentar seu melhor argumento primeiro.','Fazer a pessoa examinar os próprios critérios e perceber onde a conclusão atual não os satisfaz.','Mostrar quantas pessoas concordam com você.','Aumentar a urgência da decisão.'],skill:'Influência',w:[65,100,55,30]},
{tag:'AUTONOMIA',q:'Quando alguém sente que está sendo pressionado a escolher, o que pode acontecer mesmo que a opção seja boa?',a:['Nada, se os argumentos forem fortes.','Pode surgir resistência para preservar autonomia, fazendo a pessoa rejeitar inclusive uma opção útil.','Ela decidirá mais rápido.','A pressão aumenta percepção de valor.'],skill:'Psicologia',w:[15,100,20,25]},
{tag:'PERGUNTA',q:'Qual pergunta tende a revelar o modelo mental da pessoa, e não apenas uma preferência?',a:['Você gostou?','Qual opção você prefere?','O que você está usando como critério para decidir entre essas opções?','De zero a dez, quanto isso importa?'],skill:'Investigação',w:[20,35,100,55]},
{tag:'NEGOCIAÇÃO',q:'A outra pessoa rejeita sua proposta, mas continua fazendo perguntas detalhadas sobre implementação. O que esse comportamento sugere?',a:['A rejeição não é verdadeira.','Ela já decidiu comprar.','Existe interesse cognitivo ou uma condição ainda aberta; rejeição verbal e comportamento precisam ser investigados juntos.','Ela quer copiar a ideia.'],skill:'Negociação',w:[48,30,100,20]},
{tag:'FEEDBACK',q:'Você precisa corrigir alguém competente que cometeu um erro. Qual abordagem reduz defesa sem enfraquecer a mensagem?',a:['Começar elogiando e depois criticar.','Descrever comportamento e impacto observável, separar isso da identidade da pessoa e investigar o processo.','Ser muito direto para evitar ambiguidade.','Perguntar se ela aceita receber feedback.'],skill:'Comunicação',w:[58,100,62,70]},
{tag:'EMOÇÃO',q:'Uma pessoa diz estar tranquila, mas começa a justificar excessivamente uma decisão que ninguém questionou. O que você registra?',a:['Ela está mentindo.','A justificativa excessiva pode ser um sinal, mas não prova, de conflito interno ou necessidade de validação.','Ela é insegura.','A decisão provavelmente está errada.'],skill:'Leitura',w:[30,100,38,25]},
{tag:'PERSUASÃO',q:'Quando alguém verbaliza com as próprias palavras por que uma mudança seria importante, por que isso pode ser mais poderoso do que ouvir seu argumento?',a:['Porque a pessoa gosta de falar.','Porque razões produzidas pela própria pessoa tendem a integrar melhor seu modelo de decisão do que razões apenas recebidas.','Porque você economiza tempo.','Porque ela assume compromisso público automaticamente.'],skill:'Influência',w:[15,100,30,55]},
{tag:'VALOR',q:'Duas pessoas recebem exatamente a mesma proposta; uma acha cara e outra barata. O que isso mostra?',a:['Uma delas está errada.','Preço é objetivo, mas valor percebido depende de referência, necessidade, risco e alternativa.','A pessoa com mais dinheiro sempre percebe menor preço.','A proposta foi mal apresentada.'],skill:'Negociação',w:[15,100,25,45]},
{tag:'LEITURA SOCIAL',q:'Em um grupo, todos concordam rapidamente com a pessoa de maior status. Qual risco você considera?',a:['Nenhum, porque status costuma acompanhar competência.','Conformidade ou autocensura podem estar mascarando opiniões e informações divergentes.','O líder provavelmente preparou a decisão antes.','O grupo é eficiente.'],skill:'Psicologia',w:[15,100,35,25]},
{tag:'CONDUÇÃO',q:'Uma conversa fica emocional e começa a se afastar do problema original. Qual intervenção tende a recuperar qualidade?',a:['Voltar imediatamente aos fatos.','Reconhecer o estado emocional, separar pessoa de problema e reconstruir o ponto de decisão.','Encerrar até todos se acalmarem.','Ignorar emoção para não reforçá-la.'],skill:'Comunicação',w:[58,100,50,25]},
{tag:'MOTIVAÇÃO',q:'Uma pessoa diz querer muito um objetivo, mas evita repetidamente as ações necessárias. Qual interpretação é mais sofisticada?',a:['Ela não quer de verdade.','Ela é indisciplinada.','Pode haver conflito entre objetivos: ela deseja o resultado, mas também protege algo ameaçado pelo caminho até ele.','Ela precisa de cobrança.'],skill:'Psicologia',w:[32,28,100,40]},
{tag:'DECISÃO',q:'Alguém pede sua opinião, mas rejeita cada alternativa que você oferece. Qual pergunta pode mudar a conversa?',a:['Então por que você me perguntou?','Qual consequência você está tentando evitar independentemente da opção escolhida?','Qual opção você quer que eu escolha por você?','Você tem certeza de que quer resolver isso?'],skill:'Decisão',w:[25,100,45,52]},
{tag:'CONFIANÇA',q:'Você sente que “leu” perfeitamente uma pessoa nos primeiros minutos. Qual atitude demonstra melhor inteligência social?',a:['Confiar na intuição porque leitura rápida é importante.','Transformar a impressão em hipótese e procurar sinais que possam confirmá-la ou contradizê-la.','Não formar impressão alguma.','Perguntar diretamente se sua leitura está certa.'],skill:'Leitura',w:[48,100,40,72]},
{tag:'SÍNTESE',q:'Depois de uma conversa complexa, qual síntese mostra maior compreensão da pessoa?',a:['Listar tudo que ela disse.','Identificar o que ela quer, o que teme, quais critérios usa e onde existem contradições — distinguindo fatos de hipóteses.','Descrever sua personalidade.','Escolher a frase mais importante da conversa.'],skill:'Comunicação',w:[42,100,35,58]}
];
const skills=['Leitura','Psicologia','Investigação','Influência','Negociação','Comunicação','Decisão'];
const skillMap:Record<string,string>={Leitura:'Leitura',Psicologia:'Psicologia',Investigação:'Investigação',Influência:'Influência',Negociação:'Negociação',Comunicação:'Comunicação',Decisão:'Decisão'};

export default function Calibragem(){
 const [started,setStarted]=useState(false),[i,setI]=useState(0),[answers,setAnswers]=useState<number[]>([]);
 const done=answers.length===qs.length;
 const [saved,setSaved]=useState(false);
 const scores=useMemo(()=>Object.fromEntries(skills.map(s=>{const items=qs.map((q,idx)=>({q,idx})).filter(x=>skillMap[x.q.skill]===s&&answers[x.idx]!==undefined);if(!items.length)return[s,0];const raw=items.reduce((sum,x)=>sum+x.q.w[answers[x.idx]],0)/items.length;return[s,Math.round(raw)]})),[answers]);
 const choose=(n:number)=>{const next=[...answers,n];setAnswers(next);if(i<qs.length-1)setTimeout(()=>setI(i+1),120)};
 const performance=Math.round(Object.values(scores).reduce((a:number,b:any)=>a+Number(b),0)/skills.length)||0;
 useEffect(()=>{if(!done||saved)return;const payload={performance,scores,completedAt:new Date().toISOString()};localStorage.setItem('noza-performance-baseline',JSON.stringify(payload));window.dispatchEvent(new CustomEvent('noza:performance-updated',{detail:payload}));setSaved(true)},[done,saved,performance,scores]);
 const reset=()=>{localStorage.removeItem('noza-performance-baseline');window.dispatchEvent(new Event('noza:performance-reset'));setAnswers([]);setI(0);setSaved(false);setStarted(false)};
 return <div className="cal-shell"><AppSidebar/><main className="cal-main">
   <div className="cal-top"><span>NOZA / INTELLIGENCE SYSTEM</span><span>{started&&!done?String(i+1).padStart(2,'0')+' / '+String(qs.length).padStart(2,'0'):'BASELINE'}</span></div>
   {!started?<section className="cal-intro">
    <div className="cal-kicker"><i/> CALIBRAGEM INICIAL</div>
    <h1>Antes de evoluir sua performance,<br/><em>precisamos entender como você pensa.</em></h1>
    <p>A NOZA vai observar como você lê pessoas, interpreta sinais, identifica motivações, faz perguntas, compreende resistência, influencia decisões e raciocina sobre comportamento.</p>
    <div className="cal-domains">{skills.map((s,n)=><span key={s}><b>0{n+1}</b>{s}</span>)}</div>
    <button className="cal-start" onClick={()=>setStarted(true)}>INICIAR CALIBRAGEM <b>→</b></button>
    <small>32 cenários humanos · 7 dimensões · aproximadamente 15 minutos · leitura, psicologia e raciocínio aplicado</small>
   </section>:!done?<section className="cal-test">
    <div className="cal-progress"><i style={{width:`${((i+1)/qs.length)*100}%`}}/></div>
    <div className="cal-code">CENÁRIO {String(i+1).padStart(2,'0')} <span>— {qs[i].tag}</span></div>
    <h2>{qs[i].q}</h2>
    <p className="cal-hint">Escolha a resposta mais próxima do que você realmente faria — não do que parece ideal.</p>
    <div className="cal-options">{qs[i].a.map((a,n)=><button key={a} onClick={()=>choose(n)}><b>{String.fromCharCode(65+n)}</b><span>{a}</span><i>↗</i></button>)}</div>
   </section>:<section className="cal-result">
    <div className="cal-kicker"><i/> BASELINE 01 CONCLUÍDO</div>
    <h1>Seu número de performance<br/><em>foi identificado.</em></h1><div className="cal-performance-number"><strong>{performance}</strong><span>/100<br/>PERFORMANCE</span></div>
    <p>Este é um retrato inicial. A NOZA vai confrontar esta calibragem com evidências reais das suas próximas interações.</p>
    <div className="cal-scoregrid">{skills.map(s=><div key={s}><header><span>{s}</span><b>{scores[s]}</b></header><div><i style={{width:`${scores[s]}%`}}/></div></div>)}</div>
    <div className="cal-insight"><span>PRIORIDADE INICIAL</span><strong>Investigação antes da argumentação.</strong><p>Seu padrão sugere espaço para aprofundar contexto e critérios antes de construir a resposta. A confiança deste diagnóstico aumentará com evidências reais.</p></div>
    <button className="cal-start" onClick={reset}>RESETAR CALIBRAGEM <b>↻</b></button>
   </section>}
 </main></div>
}