'use client';
import {useEffect,useMemo,useState} from 'react';
import AppSidebar from '../AppSidebar';
import './calibragem.css';

const qs=[
{tag:'LÓGICA',q:'Considere: todo sistema que preserva uma propriedade P sob transformação T também preserva Q. O sistema A preserva Q após T. Qual conclusão é logicamente válida?',a:['A preserva P.','A provavelmente preserva P.','Não é possível inferir se A preserva P apenas dessa informação.','A não preserva P, pois Q é consequência e não causa.'],skill:'Argumentação',w:[15,45,100,30]},
{tag:'BAYES',q:'Uma condição ocorre em 1% da população. Um teste detecta 90% dos casos e gera 9% de positivos em pessoas sem a condição. Uma pessoa testou positivo. Sem calcular com precisão, qual estimativa é mais defensável?',a:['Próxima de 90%, pois essa é a sensibilidade.','Próxima de 50%, porque positivo e negativo se equilibram.','Da ordem de 10%, porque a taxa-base baixa pesa fortemente.','Acima de 99%, porque dois eventos raros coincidiram.'],skill:'Decisão',w:[20,35,100,5]},
{tag:'CAUSALIDADE',q:'Após uma empresa adotar trabalho híbrido, produtividade subiu 12%. No mesmo período, ela demitiu equipes menos produtivas e trocou seu sistema de metas. Qual afirmação é epistemicamente mais forte?',a:['O híbrido elevou a produtividade em 12%.','O híbrido contribuiu, mas não sabemos quanto.','Os dados observacionais não isolam o efeito causal do híbrido.','As demissões explicam a maior parte do aumento.'],skill:'Investigação',w:[10,55,100,30]},
{tag:'CONTRAFACTUAL',q:'Um tratamento foi seguido de melhora em 70% dos pacientes. Sem grupo de comparação, qual informação seria mais valiosa para estimar seu efeito?',a:['Quantos médicos recomendam o tratamento.','Quantos pacientes melhorariam no mesmo período sem o tratamento ou sob alternativa comparável.','A satisfação dos pacientes tratados.','Se o mecanismo biológico parece plausível.'],skill:'Investigação',w:[15,100,30,55]},
{tag:'INCERTEZA',q:'Você precisa escolher entre A e B. A tem valor esperado maior, mas sua estimativa depende de uma premissa extremamente incerta; B tem valor esperado ligeiramente menor e dados muito melhores. O que é racional?',a:['Sempre escolher A pelo maior valor esperado calculado.','Sempre escolher B por ter mais evidência.','Modelar sensibilidade à premissa e decidir considerando valor, incerteza e reversibilidade.','Tirar a média entre A e B.'],skill:'Decisão',w:[40,45,100,10]},
{tag:'ATUALIZAÇÃO',q:'Você atribui 80% de chance a uma hipótese. Surge uma evidência que seria comum se a hipótese fosse verdadeira, mas quase igualmente comum se fosse falsa. O que deveria acontecer com sua crença?',a:['Subir bastante, pois a evidência é compatível.','Cair, pois a evidência não prova nada.','Mudar pouco, porque a evidência discrimina pouco entre as hipóteses.','Voltar para 50%, pois surgiu incerteza.'],skill:'Decisão',w:[25,30,100,15]},
{tag:'ABSTRAÇÃO',q:'Um algoritmo funciona para triagem médica, concessão de crédito e detecção de fraude, embora os dados sejam completamente diferentes. Qual descrição identifica melhor uma possível estrutura comum?',a:['Todos lidam com pessoas.','Todos tentam classificar casos sob incerteza usando sinais imperfeitos e custos assimétricos de erro.','Todos precisam de inteligência artificial.','Todos possuem dados históricos.'],skill:'Comunicação',w:[20,100,30,55]},
{tag:'EVIDÊNCIA',q:'Hipótese H prevê E com probabilidade 0,8. Hipótese rival R prevê E com probabilidade 0,75. E ocorre. O que E faz?',a:['Prova H.','Favorece fortemente H.','Favorece H apenas levemente, porque E também era muito provável sob R.','Não contém informação alguma.'],skill:'Argumentação',w:[5,35,100,30]},
{tag:'VIÉS DE SELEÇÃO',q:'Uma escola observa que alunos que frequentam monitoria têm notas menores e conclui que monitoria prejudica desempenho. Qual variável oculta é imediatamente relevante?',a:['A inteligência média da escola.','Alunos com maior dificuldade podem procurar monitoria com mais frequência.','A qualidade das provas.','O número total de alunos.'],skill:'Investigação',w:[25,100,50,15]},
{tag:'PARADOXO',q:'Em cada um de dois departamentos, método A supera B. Quando os dados dos departamentos são agregados, B supera A. Antes de chamar isso de erro, o que você investiga?',a:['Se houve fraude nos dados.','Se tamanhos dos grupos e distribuição dos casos diferem entre departamentos, produzindo uma reversão agregada.','Se a média foi calculada corretamente; reversão assim é impossível.','Se A deveria ser abandonado.'],skill:'Argumentação',w:[30,100,5,10]},
{tag:'METACOGNIÇÃO',q:'Você responde corretamente 8 de 10 problemas, mas declarou 95% de confiança em todos. Outro usuário acerta 7 de 10 e distribui confiança de modo que reconhece quase todos os próprios erros. Quem demonstrou melhor metacognição?',a:['Você, porque acertou mais.','O outro usuário, porque sua confiança discrimina melhor acertos de erros.','Ambos, pois diferença de um acerto é pequena.','Não existe relação entre confiança e metacognição.'],skill:'Escuta',w:[25,100,35,5]},
{tag:'COMPRESSÃO',q:'Quatro explicações descrevem os mesmos 40 fenômenos. Uma usa 3 princípios e prevê 6 casos novos; outra usa 20 regras e explica perfeitamente apenas os 40 conhecidos. Sem outras diferenças, qual tem maior força explicativa?',a:['A de 20 regras, porque ajusta perfeitamente os dados.','A de 3 princípios, por combinar compressão e poder preditivo fora da amostra.','São equivalentes porque explicam os 40 casos.','Não se pode comparar teorias pelo número de regras.'],skill:'Comunicação',w:[20,100,35,45]},
{tag:'INFORMAÇÃO',q:'Você pode fazer apenas uma pergunta para distinguir entre duas hipóteses igualmente prováveis. Qual pergunta é mais valiosa?',a:['A que confirma a hipótese que parece intuitivamente melhor.','A cuja resposta provável seria quase igual sob ambas.','A cuja distribuição de respostas é mais diferente entre as duas hipóteses.','A mais fácil para o respondente.'],skill:'Investigação',w:[10,15,100,25]},
{tag:'FALÁCIA',q:'Se uma política funciona, observaremos queda em X. Observamos queda em X. Qual é o problema em concluir que a política funcionou?',a:['Nenhum; a previsão foi confirmada.','Confundir uma consequência prevista com evidência exclusiva da causa; outras causas também podem produzir X.','A queda deveria ter ocorrido antes da política.','Toda política possui efeitos colaterais.'],skill:'Argumentação',w:[10,100,25,15]},
{tag:'MODELO MENTAL',q:'Duas pessoas recebem os mesmos fatos e chegam a conclusões opostas sem erro lógico evidente. Qual investigação é mais informativa?',a:['Descobrir qual delas é mais inteligente.','Identificar premissas, funções de valor e probabilidades implícitas diferentes em cada modelo.','Contar quantos fatos cada uma citou.','Ver qual conclusão é mais popular.'],skill:'Escuta',w:[10,100,25,10]},
{tag:'PREVISÃO',q:'Um especialista faz 100 previsões de “70% de chance”. Aproximadamente 50 se realizam. O principal problema é:',a:['Ele errou metade das previsões.','Ele deveria prever apenas eventos certos.','Suas probabilidades estão mal calibradas: eventos chamados de 70% ocorrem perto de 50%.','Não há problema; 50 acertos é bastante.'],skill:'Decisão',w:[35,10,100,15]},
{tag:'DETECÇÃO DE SINAL',q:'Em um sistema de segurança, falso negativo custa 100 vezes mais que falso positivo. O limiar ótimo de alerta deveria ser definido principalmente por:',a:['Maximizar a porcentagem total de acertos.','Equilibrar falsos positivos e falsos negativos em 50/50.','Distribuição dos sinais, taxas-base e custos relativos dos dois tipos de erro.','Eliminar totalmente falsos negativos.'],skill:'Decisão',w:[25,15,100,50]},
{tag:'REGRESSÃO',q:'Os 10 piores desempenhos de uma equipe recebem treinamento e, no mês seguinte, melhoram. Por que isso ainda não demonstra o efeito do treinamento?',a:['Porque treinamento nunca pode ser avaliado em um mês.','Porque casos extremos tendem parcialmente a voltar à média mesmo sem intervenção.','Porque os melhores não receberam treinamento.','Porque desempenho não pode ser quantificado.'],skill:'Investigação',w:[30,100,35,5]},
{tag:'COERÊNCIA',q:'Você prefere A a B, B a C, mas C a A, sob o mesmo critério e sem mudança de informação. O padrão sugere:',a:['Flexibilidade cognitiva.','Uma preferência intransitiva que pode produzir escolhas inconsistentes.','Que as três opções têm o mesmo valor.','Que o critério é sofisticado demais para ordenar.'],skill:'Argumentação',w:[10,100,20,25]},
{tag:'DILEMA',q:'Uma regra melhora resultados médios, mas piora muito o pior caso possível. Outra reduz o resultado médio, porém limita perdas extremas. Qual escolha é racional?',a:['A primeira, sempre, porque média domina.','A segunda, sempre, porque segurança domina.','Depende da função de utilidade, tolerância a risco, probabilidade das caudas e reversibilidade.','Escolher aleatoriamente evita viés.'],skill:'Decisão',w:[20,25,100,5]},
{tag:'SEMÂNTICA',q:'“A maioria dos erros ocorreu em decisões rápidas.” Qual conclusão NÃO está autorizada por essa frase?',a:['Houve erros em decisões rápidas.','Decisões rápidas causaram a maioria dos erros.','Podemos investigar a proporção de decisões rápidas entre todas as decisões.','Precisamos de denominadores para comparar taxas de erro.'],skill:'Comunicação',w:[55,100,80,85]},
{tag:'ANALOGIA',q:'Uma analogia é estruturalmente forte quando:',a:['Os objetos comparados se parecem visualmente.','Compartilham relações causais ou funcionais relevantes, mesmo com elementos superficiais diferentes.','Usa exemplos conhecidos.','Produz uma explicação intuitiva.'],skill:'Comunicação',w:[15,100,35,40]},
{tag:'DADOS AUSENTES',q:'Uma pesquisa de satisfação recebe resposta de 18% dos clientes e mostra 92% de satisfação. Qual é a questão crítica?',a:['A amostra é necessariamente pequena demais.','Se a probabilidade de responder está relacionada à satisfação, gerando viés de não resposta.','Se 92% deveria ser arredondado.','Se os clientes conhecem o produto suficientemente.'],skill:'Investigação',w:[45,100,10,30]},
{tag:'CONJUNÇÃO',q:'Uma descrição detalhada torna duas características simultâneas muito representativas de uma pessoa. Comparada à probabilidade de apenas uma dessas características, a probabilidade das duas juntas é:',a:['Maior se a descrição combinar bem.','No máximo igual à probabilidade da característica isolada.','Sempre metade.','Impossível comparar sem conhecer a pessoa.'],skill:'Decisão',w:[10,100,15,35]},
{tag:'EXPLICAÇÃO',q:'Um modelo acrescenta uma variável nova e passa de 91% para 91,4% de acerto no conjunto usado para construí-lo. O que falta antes de dizer que melhorou?',a:['Nada; 0,4 ponto já é melhoria.','Testar generalização fora da amostra e considerar complexidade/overfitting.','Saber o nome da variável.','Aumentar a precisão decimal.'],skill:'Argumentação',w:[10,100,5,5]},
{tag:'CRENÇA',q:'Qual evidência deveria fazer você revisar mais fortemente uma crença?',a:['Uma evidência que você já esperava independentemente de a crença ser verdadeira.','Uma evidência muito provável se sua crença for verdadeira e muito improvável se ela for falsa.','Muitas pessoas concordando com você.','Uma explicação elegante compatível com a crença.'],skill:'Persuasão',w:[15,100,25,45]},
{tag:'DESACORDO',q:'Você e outra pessoa igualmente informada chegam a probabilidades muito diferentes. Antes de persuadi-la, o melhor próximo passo é:',a:['Apresentar sua evidência mais forte.','Localizar exatamente qual premissa, evidência ou atualização produz a divergência.','Comparar currículos para decidir quem pesa mais.','Buscar uma terceira opinião que desempate.'],skill:'Escuta',w:[55,100,15,40]},
{tag:'REVISÃO',q:'Você descobre que uma fonte central da sua conclusão era menos confiável do que pensava. Uma boa atualização exige:',a:['Descartar toda a conclusão.','Recalcular quanto aquela fonte contribuía e propagar a mudança pelo restante do raciocínio.','Manter a conclusão se outras fontes concordam.','Trocar a fonte por outra que sustente a mesma tese.'],skill:'Persuasão',w:[30,100,50,5]},
{tag:'PROBLEMA INVERSO',q:'Você observa um efeito final que poderia ser produzido por cinco mecanismos diferentes. Qual estratégia reduz melhor a ambiguidade?',a:['Escolher o mecanismo mais comum.','Buscar uma observação que os mecanismos prevejam de maneira diferente.','Combinar os cinco em uma explicação única.','Escolher o mecanismo mais simples.'],skill:'Investigação',w:[35,100,20,60]},
{tag:'DECISÃO SEQUENCIAL',q:'Você pode obter nova informação amanhã por baixo custo, mas decidir hoje é irreversível. O que importa além do valor esperado atual?',a:['Somente a urgência subjetiva.','O valor esperado da informação e o custo da irreversibilidade.','A confiança da pessoa que propôs decidir hoje.','Quantas opções existem.'],skill:'Decisão',w:[10,100,15,20]},
{tag:'ARGUMENTO',q:'Uma conclusão pode ser verdadeira mesmo quando o argumento usado para defendê-la é inválido. O que isso implica para avaliação?',a:['Se a conclusão é verdadeira, o argumento é aceitável.','Precisamos avaliar separadamente validade da inferência e verdade das premissas/conclusão.','Argumentos só importam quando a conclusão é falsa.','Uma conclusão verdadeira torna premissas provavelmente verdadeiras.'],skill:'Argumentação',w:[10,100,5,20]},
{tag:'META-RACIOCÍNIO',q:'Em qual situação reduzir sua confiança é sinal de melhor raciocínio, e não de pior desempenho?',a:['Quando você quer parecer humilde.','Quando descobre que o problema possui variáveis relevantes que seu modelo não representa.','Sempre que alguém discorda.','Quando demora muito para responder.'],skill:'Escuta',w:[5,100,20,25]}
];
const skills=['Raciocínio','Metacognição','Probabilidade','Causalidade','Abstração','Evidência','Decisão','Comunicação'];
const skillMap:Record<string,string>={Argumentação:'Raciocínio',Escuta:'Metacognição',Decisão:'Probabilidade',Investigação:'Causalidade',Comunicação:'Abstração',Persuasão:'Evidência',Negociação:'Decisão',Condução:'Comunicação'};

export default function Calibragem(){
 const [started,setStarted]=useState(false),[i,setI]=useState(0),[answers,setAnswers]=useState<number[]>([]);
 const done=answers.length===qs.length;
 const [saved,setSaved]=useState(false);
 const scores=useMemo(()=>Object.fromEntries(skills.map(s=>{const items=qs.map((q,idx)=>({q,idx})).filter(x=>skillMap[x.q.skill]===s&&answers[x.idx]!==undefined);if(!items.length)return[s,0];const raw=items.reduce((sum,x)=>sum+x.q.w[answers[x.idx]],0)/items.length;return[s,Math.round(raw)]})),[answers]);
 const choose=(n:number)=>{const next=[...answers,n];setAnswers(next);if(i<qs.length-1)setTimeout(()=>setI(i+1),120)};
 const performance=Math.round(Object.values(scores).reduce((a:number,b:any)=>a+Number(b),0)/skills.length)||0;
 useEffect(()=>{if(!done||saved)return;const payload={performance,scores,completedAt:new Date().toISOString()};localStorage.setItem('noza-performance-baseline',JSON.stringify(payload));window.dispatchEvent(new CustomEvent('noza:performance-updated',{detail:payload}));setSaved(true)},[done,saved,performance,scores]);
 const reset=()=>{localStorage.removeItem('noza-performance-baseline');window.dispatchEvent(new Event('noza:performance-reset'));setAnswers([]);setI(0);setSaved(false);setStarted(false)};
 return <div className="cal-shell"><AppSidebar/><main className="cal-main">
   <div className="cal-top"><span>NOZA / INTELLIGENCE SYSTEM</span><span>{started&&!done?String(i+1).padStart(2,'0')+' / '+String(qs.length).padStart(2,'0'):'BASELINE'}</span></div>
   {!started?<section className="cal-intro">
    <div className="cal-kicker"><i/> CALIBRAGEM INICIAL</div>
    <h1>Antes de evoluir sua performance,<br/><em>precisamos entender como você pensa.</em></h1>
    <p>A NOZA vai observar como você infere, atualiza crenças, distingue correlação de causalidade, raciocina sob incerteza, abstrai estruturas e calibra a própria confiança.</p>
    <div className="cal-domains">{skills.map((s,n)=><span key={s}><b>0{n+1}</b>{s}</span>)}</div>
    <button className="cal-start" onClick={()=>setStarted(true)}>INICIAR CALIBRAGEM <b>→</b></button>
    <small>32 problemas cognitivos · 8 dimensões · aproximadamente 18 minutos · raciocínio, não conhecimento decorado</small>
   </section>:!done?<section className="cal-test">
    <div className="cal-progress"><i style={{width:`${((i+1)/qs.length)*100}%`}}/></div>
    <div className="cal-code">CENÁRIO {String(i+1).padStart(2,'0')} <span>— {qs[i].tag}</span></div>
    <h2>{qs[i].q}</h2>
    <p className="cal-hint">Escolha a resposta mais próxima do que você realmente faria — não do que parece ideal.</p>
    <div className="cal-options">{qs[i].a.map((a,n)=><button key={a} onClick={()=>choose(n)}><b>{String.fromCharCode(65+n)}</b><span>{a}</span><i>↗</i></button>)}</div>
   </section>:<section className="cal-result">
    <div className="cal-kicker"><i/> BASELINE 01 CONCLUÍDO</div>
    <h1>Seu número de performance<br/><em>foi identificado.</em></h1><div className="cal-performance-number"><strong>{performance}</strong><span>/100<br/>PERFORMANCE</span></div>
    <p>Este é um retrato inicial. A NOZA vai confrontar esta calibragem com evidências reais das suas próximas interações.</p>
    <div className="cal-scoregrid">{skills.map(s=><div key={s}><header><span>{s}</span><b>{scores[s]}</b></header><div><i style={{width:`${scores[s]}%`}}/></div></div>)}</div>
    <div className="cal-insight"><span>PRIORIDADE INICIAL</span><strong>Investigação antes da argumentação.</strong><p>Seu padrão sugere espaço para aprofundar contexto e critérios antes de construir a resposta. A confiança deste diagnóstico aumentará com evidências reais.</p></div>
    <button className="cal-start" onClick={reset}>RESETAR CALIBRAGEM <b>↻</b></button>
   </section>}
 </main></div>
}